@echo off
:: Get the list of connected devices
:: Generated by AI Copilot
for /f "tokens=1" %%a in ('adb devices ^| findstr /v "List"') do (
    set device=%%a
)

:: Check if a device ID is retrieved
if "%device%"=="" (
    echo No device found.
    pause
    exit /b
)

:: Map the ports for the retrieved device ID
adb -s %device% reverse tcp:4200 tcp:4200
echo Port mapping done for device %device%.

pause