name: Deploy Ball-Game to Netlify

on:
  push:
    paths:
      - "games/running-ball-babylonjs/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Netlify
        run: npm install netlify-cli -g
        working-directory: ./games/running-ball-babylonjs

      - name: Install Dependencies
        run: npm ci
        working-directory: ./games/running-ball-babylonjs

      - name: Deploy to Netlify
        id: netlify_deploy
        working-directory: ./games/running-ball-babylonjs
        run: |
          netlify deploy \
            --dir dist \
            --site ${{ secrets.GAME_RUNNING_BALL_NETLIFY_PROJECT_ID }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \
            --prod
